[tox]
envlist = typing,black,isort,py311,py312,py313,py314
skip_missing_interpreters = true
requires =
    tox>=4.53.0

[flake8]
# IGNORE THESE ERRORS.
#   D: flake8-docstrings/pydocstyle - http://pep257.readthedocs.io/en/latest/error_codes.html
#   H: hacking/openstack python style guide
#   P: flake8-string-format
#   S: flake8-pep3101 (% vs str.format())
#   W: flake8 whitespace
# D100: Missing docstring in public module
# D104: Missing docstring in public package
# D105: Missing docstring in magic method
# D200: One-line docstring should fit on one line with quotes
# D204: 1 blank line required after class docstring
# D205: 1 blank line required between summary line and description
# D301: Use r""" if any backslashes in a docstring
# D302: Use u""" for Unicode docstrings
# D400: First line should end with a period
# D401: First line should be in imperative mood
# D402: First line should not be the function's "signature"
# D403: First word of the first line should be properly capitalized
# D404: First word of the docstring should not be `This`
# E741 ambiguous variable name
# H101: Use TODO(NAME)
# H301: one import per line
# H306: imports not in alphabetical order (time, os)
# H401: docstring should not start with a space
# H404: multi line docstring should start without a leading new line
# H405: multi line docstring summary not separated with an empty line
# N804: first argument of a classmethod should be named 'cls'
# N805: first argument of a method should be named 'self'
# P102: docstring does contain unindexed parameters
# P302: format call provides unused keyword (e.g. 'exc_info')
# S001: found module formatter
# W503: Line break before binary operator
# W504: line break after binary operator
ignore = D100,D104,D105,D200,D204,D205,D301,D302,D400,D401,D402,D403,D404,E741,H101,H301,H306,H401,H404,H405,N804,N805,P102,W291,P302,S001,W503,W504,E122,W605,F541,E231,E241,E128,E501,E125,E126
inline_quotes = double
max_line_length = 120

[testenv]
allowlist_externals = pytest,black,mypy,flake8
dependency_groups =
    dev
set_env =
    PYTHONHOME =
    PYTHONPATH =
    PYTHONUSERBASE =
    PYTHONNOUSERSITE = 1
commands = pytest -s -vv --junitxml=junit.xml -o junit_family=legacy tests/

[testenv:py311]
basepython = python3.11

[testenv:py312]
basepython = python3.12

[testenv:py313]
basepython = python3.13

[testenv:py314]
basepython = python3.14

[testenv:black]
deps = black>=26.3.1
commands = black --check src tests

[testenv:isort]
deps = isort>=8.0.1
commands = isort --check-only src tests

[testenv:flake8]
deps = flake8>=7.3.0
       flake8-pyproject>=1.2.4
commands = flake8 src tests

[testenv:typing]
deps = mypy>=1.20.1
       types-requests
       types-toml
       types-pyyaml
commands = mypy src